### ISSUE TITLE
Implement CI discovery provider

### ISSUE THREAD

**Issue by ostridm** [NeuraLegion/sectester-net#88]
Implement CI Discovery provider compatible with [ci-info](https://github.com/watson/ci-info) package which is used by sectester-js

**Comment by derevnjuk** [comment]
@ostridm  you don't change API nor change the behavior, this is refactoring

**Comment by derevnjuk** [comment]
@ostridm you know, I would say this is still `refactor` since `CIDiscovery` is internal
